# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88956fe5b3a0869817a8187dc1bffdfe07bb031dee0c165e2f8509685bc38578cfe0192182dfde106d2a71f45f9ca0cd3982e47b37f924d19d4a1717662433d1

test:
  secret_key_base: f9368f5515de0cc33fd230513d664ee6b86508894e789215ee421748d29cf5228158c6bbbdfe463778315fe8f3b784778be0dc5415f2841b3d1733f85c88bdde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
